services:
  app:
    build:
      context: .
      args:
        JC_PASSWORD: ${JC_PASSWORD}
        ALVARO_PASSWORD: ${ALVARO_PASSWORD}
    container_name: dev-env
    hostname: yharnam
    env_file:
      - .env
    volumes:
      - /home/j/Desarrollo/:/usr/src/app/workspace
    stdin_open: true
    tty: true
    user: "jc"
#    command: bash -c "sudo chown -R jc:jc /usr/src/app/workspace && bash"
    entrypoint: ["bash", "-c", "sudo chown -R jc:jc /usr/src/app/workspace && bash"]
